### ISSUE TITLE
New Feature Request or Contributions are Welcome !!!

### ISSUE THREAD

**Issue by BRAVO68WEB** [DFCommunity/Hexo-Web-Nary#3]
Hello all! I'm @BRAVO68WEB ! Contributions are now open for our project repo! Anyone want to contribute something to the project are now welcome here! Happy hacking! xD

**Comment by imakumar98** [comment]
@BRAVO68WEB assign this issue to me, I'll work on it

**Comment by BRAVO68WEB** [comment]
Ok sure

**Comment by BRAVO68WEB** [comment]
@imakumar98 Any update?
